### ISSUE TITLE
Order lab dan radiologi dari form asesmen dokter tidak bisa

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#394]
Form tambah pemeriksaan LABORATORIUM DAN RADIOLOGI. Saat diklik order, nama pemeriksaan tidak tampil di list orderan lab maupun radiologi 
![image](https://user-images.githubusercontent.com/15723622/129530781-3b974d68-dc58-47d4-8a8e-de17095d15d2.png)

https://user-images.githubusercontent.com/15723622/129530791-0a2693aa-b217-4b84-b3a2-f165574e4329.mp4

https://user-images.githubusercontent.com/15723622/129530797-c7742773-b243-49ba-afd3-821aaa423c46.mp4

**Comment by theycantrevealus** [comment]
Hasil pegujian remote
Penambahan order labor a/n **SUHARTO** 2x
![Screenshot from 2021-08-16 14-21-26](https://user-images.githubusercontent.com/44671357/129531901-509bdb8e-52f6-4f0b-b1fc-5c05014cf2be.png)

Hasil pada labor
![Screenshot from 2021-08-16 15-06-51](https://user-images.githubusercontent.com/44671357/129531930-f3a7047d-88a4-4c63-b494-4e7818cf5c7d.png)

Juga di order radio atas nama **SUHARTO**
![Screenshot from 2021-08-16 15-07-09](https://user-images.githubusercontent.com/44671357/129532000-ee733466-cd63-4ca5-bbc5-b0970fe37621.png)
