### ISSUE TITLE
Resep IGD dan Ranap. tidak bisa simpan di menu proses resep

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#395]
Di menu proses Resep, Setelah klik simpan nama pasien tidak masuk di penyerahan resep 

https://user-images.githubusercontent.com/15723622/129531288-589a3592-f31f-4ea3-ab72-772089b7174a.mp4

https://user-images.githubusercontent.com/15723622/129531292-5a760ef7-51bc-420b-ba25-ec5f3105d4c5.mp4

**Comment by theycantrevealus** [comment]
Hal yang sama tentang cache. Sudah kami tambahkan logika untuk melakukan validasi data cache dengan data di server dan replace data yang benar. Berikut hasil uji di server

Proses Resep
![Screenshot from 2021-08-16 15-34-45](https://user-images.githubusercontent.com/44671357/129535536-2c6a2897-7376-4a99-8aee-5b4d71e4cb15.png)

Setelah di proses, list albert hilang
![Screenshot from 2021-08-16 15-35-00](https://user-images.githubusercontent.com/44671357/129535573-18a6f121-6288-46c6-9673-5b19a1ded848.png)

Muncul di penyerahan
![Screenshot from 2021-08-16 15-35-06](https://user-images.githubusercontent.com/44671357/129535596-e8246783-cca0-44ab-9de6-b16e22285cdc.png)

Check Obat
![Screenshot from 2021-08-16 15-35-11](https://user-images.githubusercontent.com/44671357/129535612-eea1dc71-e840-4b62-9181-8ca139a27e14.png)

Masuk ke mutasi Apotek - IGD
![Screenshot from 2021-08-16 15-35-24](https://user-images.githubusercontent.com/44671357/129535674-e567cc70-7ce0-43d0-b1f3-ec36ec700fb9.png)
