### ISSUE TITLE
[IGD] dimenu verifikasi, nama pasien tidak hilang dari list stelah diverifikasi (a.n sopirman lase)

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#411]
![sopirman](https://user-images.githubusercontent.com/15723622/129855381-955aa3d2-5e87-45d4-9683-c03ccb4d38d5.png)

https://user-images.githubusercontent.com/15723622/129855386-f934faf0-a76a-4bda-ada3-ca18b2569ad2.mp4

![supirman jadi double](https://user-images.githubusercontent.com/15723622/129855400-5c0e0274-7693-43fa-a8e1-4029d03a0937.png)
di proses resep. karena telah berkali kali dicoba verifikasi. item obat di proses resep menjadi berganda

**Comment by theycantrevealus** [comment]
![Screenshot from 2021-08-18 15-18-34](https://user-images.githubusercontent.com/44671357/129863620-e3484f0f-1531-4e29-ab03-9c2d6df2b8fe.png)
Done. Mode uji jadi sementara diaktifkan semua resep IGD. Sudah dikembalikan ke mode normal

**Comment by ujo85** [comment]
sep mantap
