### ISSUE TITLE
Jika di kasir pasien hanya membayar salah satu atau beberapa obat 

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#416]
Jika di kasir pasien hanya membayar salah satu atau beberapa obat. Di proses resep apotek keseluruhan obat tetap masuk walaupun tidak dibayarkan di kasir.

https://user-images.githubusercontent.com/15723622/130033898-85a21d83-45d7-4cfd-bf33-0dc330dac909.mp4

**Comment by theycantrevealus** [comment]
Sesuai dengan ketentuan perobatan. Variasi obat dari dokter tidak dapat dikurangi pada saat pembayaran. Resep dokter merupakan satu paket yang harus lengkap obat nya. Yang dapat dikurangi hanya jumlah obat. Maka dari itu UX menjadi

Klik 1 obat, maka semua obat akan tercentang untuk dibayarkan, begitu juga sebaliknya. Sehingga tidak ada obat yang tidak dibayar. Petugas verifikasi harus melakukan edukasi dan informasi harga dulu kepada pasien serta memastikan obat mampu dibayar oleh pasien pada saat itu. Jika terjadi kasus tidak mampu dapat menggunakan fitur copy resep.

![Screenshot from 2021-08-19 22-10-41](https://user-images.githubusercontent.com/44671357/130094125-84527e2f-bdc9-4d1a-b52f-4f9eb089189e.png)
