### ISSUE TITLE
Opsi pembatalan di menu verifikasi laboratorium dan radiologi oleh kepala ruangan

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#417]

**Comment by theycantrevealus** [comment]
Mohon dirumuskan secara terperinci sebagai requirement bagi kami.
Apakah hanya sekedar di batalkan saja?
Jika salah batalkan siapa otoritas yang bisa membalikkan data nya? Karena tidak mungkin harus order ulang lagi kn? Dokter akan complain. Mohon informasi lengkap mengenai rumusan ini.

Rangkuman mengenai issue ini adalah
1. Verifikator/Karu yg membatalkan pesanan, pasti dengan alasan.

2. Siapa otoritas yang dapat membalikkan data yang dibatalkan. Dalam hal ini ada kemungkinan permainan lapangan, apakah harus ada preventasi atau ketentuan? Cthnya batasan waktu? Atau ada batasan lainnya?

**Comment by septia-anugrah** [comment]
> Mohon dirumuskan secara terperinci sebagai requirement bagi kami.
> Apakah hanya sekedar di batalkan saja?
> Jika salah batalkan siapa otoritas yang bisa membalikkan data nya? Karena tidak mungkin harus order ulang lagi kn? Dokter akan complain. Mohon informasi lengkap mengenai rumusan ini.
> 
> Rangkuman mengenai issue ini adalah
> 
> 1. Verifikator/Karu yg membatalkan pesanan, pasti dengan alasan.
> 2. Siapa otoritas yang dapat membalikkan data yang dibatalkan. Dalam hal ini ada kemungkinan permainan lapangan, apakah harus ada preventasi atau ketentuan? Cthnya batasan waktu? Atau ada batasan lainnya?

Answer :
1. Yang dapat membatalkan karu dan harus dengan alasan
Karu radiologi : Romi Andika
Karu laboratorium : Dumasari

2. Untuk lebih aman. Orderan yang dapat dihapus adalah orderan yang sudah lebih dari 1 bulan berada di list verifikasi. Tentunya sebelum menghapus karu akan melakukan investigasi kenapa orderan tersebut belum diverifikasi lebih dari 1 bulan.

3. Yang bisa mengembalikan orderan yang sudah terlanjur dibatalkan adalah admin dilengkapi dengan alasan kenapa dikembalikan. Dalam aksinya admin harus menerima surat permohonan pengembalian orderan yang batal dari karu terlebih dahulu

**Comment by theycantrevealus** [comment]
Baik bang. Akan kami catat sebagai requirement. Jika sudah lengkap mohon konfirmasi bang agar bisa mulai dikerjakan. Atas persetujuan dari Bg Fauzan dan Bg Jo maka akan saya lanjut kerjakan

**Comment by theycantrevealus** [comment]
Linked Issue similiar to #404

**Comment by ujo85** [comment]
Untuk lebih aman. Orderan yang dapat dihapus adalah orderan yang sudah lebih dari 1 bulan berada di list verifikasi. Tentunya sebelum menghapus karu akan melakukan investigasi kenapa orderan tersebut belum **diverifikasi lebih dari 1 bulan**.

Kira2 kenapa ya bisa 1 bulan lebih ngak di verif?

**Comment by septia-anugrah** [comment]
> Untuk lebih aman. Orderan yang dapat dihapus adalah orderan yang sudah lebih dari 1 bulan berada di list verifikasi. Tentunya sebelum menghapus karu akan melakukan investigasi kenapa orderan tersebut belum **diverifikasi lebih dari 1 bulan**.
> 
> Kira2 kenapa ya bisa 1 bulan lebih ngak di verif?

Bisa karena orderannya terbuat dua kali oleh dokter bang. Jadi hanya salah satu orderan yang di verifikasi dan satu lagi tidak. 
Dan bisa karena pasien tidak ingin melakukan pemeriksaan dan langsung pulang setelah konsultasi tanpa konfirmasi ke lab atau radiologi sehingga menggantung di verifikasi

**Comment by ujo85** [comment]
> > Untuk lebih aman. Orderan yang dapat dihapus adalah orderan yang sudah lebih dari 1 bulan berada di list verifikasi. Tentunya sebelum menghapus karu akan melakukan investigasi kenapa orderan tersebut belum **diverifikasi lebih dari 1 bulan**.
> > Kira2 kenapa ya bisa 1 bulan lebih ngak di verif?
> 
> Bisa karena **orderannya terbuat dua kali oleh dokter** bang. Jadi hanya salah satu orderan yang di verifikasi dan satu lagi tidak.
> Dan bisa karena pasien tidak ingin melakukan pemeriksaan dan langsung pulang setelah konsultasi tanpa konfirmasi ke lab atau radiologi sehingga menggantung di verifikasi

berarti permasalahan nya ada di "orderannya terbuat dua kali oleh dokter", kira2 kenapa bisa terjadi seperti itu ya?

**Comment by septia-anugrah** [comment]
> > > Untuk lebih aman. Orderan yang dapat dihapus adalah orderan yang sudah lebih dari 1 bulan berada di list verifikasi. Tentunya sebelum menghapus karu akan melakukan investigasi kenapa orderan tersebut belum **diverifikasi lebih dari 1 bulan**.
> > > Kira2 kenapa ya bisa 1 bulan lebih ngak di verif?
> > 
> > 
> > Bisa karena **orderannya terbuat dua kali oleh dokter** bang. Jadi hanya salah satu orderan yang di verifikasi dan satu lagi tidak.
> > Dan bisa karena pasien tidak ingin melakukan pemeriksaan dan langsung pulang setelah konsultasi tanpa konfirmasi ke lab atau radiologi sehingga menggantung di verifikasi
> 
> berarti permasalahan nya ada di "orderannya terbuat dua kali oleh dokter", kira2 kenapa bisa terjadi seperti itu ya?

Itu worst case yang mungkin terjadi dilapangan bang. Dan kemungkinan itu bisa terjadi apalagi di awal awal implementasi bang. Kalau menurut perspektif abang bagaimana cara untuk mengatasi hal ini bang?

**Comment by ujo85** [comment]
> > > > Untuk lebih aman. Orderan yang dapat dihapus adalah orderan yang sudah lebih dari 1 bulan berada di list verifikasi. Tentunya sebelum menghapus karu akan melakukan investigasi kenapa orderan tersebut belum **diverifikasi lebih dari 1 bulan**.
> > > > Kira2 kenapa ya bisa 1 bulan lebih ngak di verif?
> > > 
> > > 
> > > Bisa karena **orderannya terbuat dua kali oleh dokter** bang. Jadi hanya salah satu orderan yang di verifikasi dan satu lagi tidak.
> > > Dan bisa karena pasien tidak ingin melakukan pemeriksaan dan langsung pulang setelah konsultasi tanpa konfirmasi ke lab atau radiologi sehingga menggantung di verifikasi
> > 
> > 
> > berarti permasalahan nya ada di "orderannya terbuat dua kali oleh dokter", kira2 kenapa bisa terjadi seperti itu ya?
> 
> Itu worst case yang mungkin terjadi dilapangan bang. Dan kemungkinan itu bisa terjadi apalagi di awal awal implementasi bang. Kalau menurut perspektif abang bagaimana cara untuk mengatasi hal ini bang?

pertanyaan bagus, kalau menurut saya IMHO yang perlu di batasi adalah tindakan dokter jangan sampai bisa membuat 2 order pada satu kali pelayanan pada satu pasien, mungkin di kasih "peringatan" atau lain hal.

**Comment by theycantrevealus** [comment]
> > > > > Untuk lebih aman. Orderan yang dapat dihapus adalah orderan yang sudah lebih dari 1 bulan berada di list verifikasi. Tentunya sebelum menghapus karu akan melakukan investigasi kenapa orderan tersebut belum **diverifikasi lebih dari 1 bulan**.
> > > > > Kira2 kenapa ya bisa 1 bulan lebih ngak di verif?
> > > > 
> > > > 
> > > > Bisa karena **orderannya terbuat dua kali oleh dokter** bang. Jadi hanya salah satu orderan yang di verifikasi dan satu lagi tidak.
> > > > Dan bisa karena pasien tidak ingin melakukan pemeriksaan dan langsung pulang setelah konsultasi tanpa konfirmasi ke lab atau radiologi sehingga menggantung di verifikasi
> > > 
> > > 
> > > berarti permasalahan nya ada di "orderannya terbuat dua kali oleh dokter", kira2 kenapa bisa terjadi seperti itu ya?
> > 
> > 
> > Itu worst case yang mungkin terjadi dilapangan bang. Dan kemungkinan itu bisa terjadi apalagi di awal awal implementasi bang. Kalau menurut perspektif abang bagaimana cara untuk mengatasi hal ini bang?
> 
> pertanyaan bagus, kalau menurut saya IMHO yang perlu di batasi adalah tindakan dokter jangan sampai bisa membuat 2 order pada satu kali pelayanan pada satu pasien, mungkin di kasih "peringatan" atau lain hal.

Pengecekan order dengan item unik sudah ada di sistem (pada halaman order dokter). Sehingga kemungkinan pembatalan hanya ada:
1. Dokter salah pilih tindakan labor/radio.
2. Pasien berubah pikiran (Tidak jadi periksa).
3. Pasien tidak ada kabar (Pulang / Tidak datang ke verifikasi). Untuk item ini, perlu kajian dari kondisi lapangan untuk mengetahui parameter kondisinya.

Untuk beberapa item di atas lebih baik dikaji ulang dan disepakati dalam bentuk tertulis sebagai pedoman pengerjaan. Apakah ada SOP dari manajemen untuk hal ini?
