### ISSUE TITLE
Tanggal kedaluarsa di PO tidak bisa pilih tanggal. jika tanggal tidak dipilih, form PO tidak bisa disimpan

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#418]
https://user-images.githubusercontent.com/15723622/130177700-257f0efc-57f1-4b7d-9c90-05ab576d75c8.mp4

Jika bisa tanggalnya dibuat format dd/mm/yyyy

**Comment by theycantrevealus** [comment]
Linked to #386
