### ISSUE TITLE
Range harga pemeriksaan radiologi tidak tampil saat pemilihan item pemeriksaan

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#419]
![image](https://user-images.githubusercontent.com/15723622/130309916-93db6363-e7de-4ff2-b7e5-a616b198c119.png)
Berfungsi bagi dokter untuk memberitahukan perkiraan biaya pemeriksaan radiologi
![image](https://user-images.githubusercontent.com/15723622/130309921-107624ba-8bda-40ab-b84b-208628accac3.png)
Karena jika range harga hanya muncul setelah di order. Dokter tidak bisa memperingatkan biaya apalagi jika harganya mahal

**Comment by theycantrevealus** [comment]
Linked to #420
