### ISSUE TITLE
Harga yang ditampilkan saat pemilihan item pemeriksaan lab bukan format harga range

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#420]
![image](https://user-images.githubusercontent.com/15723622/130309947-1d5f4499-bd10-4a6b-8047-1f770efe2abe.png)
Harga darah lengkap disini bukan range
![image](https://user-images.githubusercontent.com/15723622/130309952-a5025ea9-43c2-489d-bd4b-faa832314d3e.png)
Jika bisa disamakan dengan tampilan setelah order. Yaitu rangenya 71.000 – 75.000

**Comment by theycantrevealus** [comment]
Pemesanan Labor Dokter
![Screenshot from 2021-08-21 15-37-39](https://user-images.githubusercontent.com/44671357/130316146-c7478a38-26b6-4e8a-a036-70feb2c63681.png)

Hasil Pemesanan Labor Dokter
![Screenshot from 2021-08-21 15-37-44](https://user-images.githubusercontent.com/44671357/130316153-c2e3d279-4a3c-4e6a-96af-bba80b243d2d.png)

Pemesanan Radiologi Dokter
![Screenshot from 2021-08-21 15-38-17](https://user-images.githubusercontent.com/44671357/130316166-f0e48440-a492-4db9-841e-be4f03ef38ac.png)

Hasil Pemesanan Radiologi Dokter
![Screenshot from 2021-08-21 15-38-22](https://user-images.githubusercontent.com/44671357/130316175-4002b24c-3091-475a-9ff1-75bdacd52226.png)
