### ISSUE TITLE
Untuk tulisan pelayanan jika bisa diubah menjadi rawat jalan, untuk memudahkan dokter mengindetifikasi pelayanan yang sedang dilakukannya

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#421]
![image](https://user-images.githubusercontent.com/15723622/130309966-1707916c-b91f-48ad-84b5-758d562a39e7.png)

**Comment by theycantrevealus** [comment]
Untuk perubahan menu dapat dilakukan di otoritas administrator menu **Modul & Menu** kemudian edit menu yang akan diubah informasinya, urutannya, iconnya(Material Name) serta redirectnya
