### ISSUE TITLE
Setelah pendaftaran pasien IGD. Nama pasien tidak muncul di list dokter IGD

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#422]
![image](https://user-images.githubusercontent.com/15723622/130309983-90684fed-4abe-48e3-afeb-4922cbc6b880.png)

https://user-images.githubusercontent.com/15723622/130309990-0070063f-c719-4b09-94a4-a42589578f5d.mp4

https://user-images.githubusercontent.com/15723622/130309994-6ecf4d66-de4f-4ef9-aa29-59b33c9561ae.mp4

**Comment by theycantrevealus** [comment]
Salah menu bang, di IGD masuknya seharusnya

**Comment by theycantrevealus** [comment]
Pendaftaran Ratna Baduman
![Screenshot from 2021-08-21 11-58-08](https://user-images.githubusercontent.com/44671357/130311065-bf119c29-3e6c-4329-b1a0-a952a6f69ba9.png)

Antrian IGD Ratna Baduman
![Screenshot from 2021-08-21 11-58-48](https://user-images.githubusercontent.com/44671357/130311074-267de693-4fc4-4f16-9b52-4e8e2092fb0d.png)

Menu IGD -> Dokter.
Struktur sama dengan rawat inap

**Comment by septia-anugrah** [comment]
oke bang. salah pilih menu tadi
