### ISSUE TITLE
[Rawat Inap] Tombol berikan obat sudah aktif pada resep yang ada obat racikannya walaupun belum dilakukan penerimaan mutasi oleh perawat

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#423]
![image](https://user-images.githubusercontent.com/15723622/130310014-d402246e-1b80-4809-902d-f9ab01ce89fc.png)
Terlihat tombol mutasi belum ditekan oleh perawat tetapi tombol berikan obat sudah aktif 

![image](https://user-images.githubusercontent.com/15723622/130310019-5f050abf-728e-4504-950c-2bf34db61b78.png)
Sedangkan jika tidak ada obat racikan tombol berikan tidak akan muncul sebelum perawat menerima mutasi

**Comment by theycantrevealus** [comment]
Test Case
1. Dipindahkan dari IGD pasien a.n. **RATNA BADUMAN**
![Screenshot from 2021-08-21 13-35-18](https://user-images.githubusercontent.com/44671357/130313295-67971064-243a-4385-8d4f-34a190621247.png)

2. Dokter memesan obat
![Screenshot from 2021-08-21 13-36-31](https://user-images.githubusercontent.com/44671357/130313306-5af83018-1946-42ff-ac9d-8a825ffdf15c.png)
Fenobarbital 4 dan Parasetamol 5
![Screenshot from 2021-08-21 13-36-49](https://user-images.githubusercontent.com/44671357/130313327-b0e15dcd-0bc9-4801-8a0f-d362c08329b0.png)

3. Verifikasi Resep
![Screenshot from 2021-08-21 13-37-18](https://user-images.githubusercontent.com/44671357/130313329-288ea8b4-b1cd-4adb-b894-1472438db222.png)

4. Setelah diproses akan permintaan mutasi (Harus di approve oleh gudang tujuan baru barang dipindahkan)
![Screenshot from 2021-08-21 13-38-29](https://user-images.githubusercontent.com/44671357/130313342-74b40ad4-b29b-4960-be1d-c91c5e6096e3.png)

5. Terlihat belum ada pemotongan stok sebanyak 4 pada obat fenobarbital
![Screenshot from 2021-08-21 13-39-03](https://user-images.githubusercontent.com/44671357/130313352-c7a7d45f-f99f-4a50-a74c-3528918241c4.png)

6. Pada halaman perawat pemberian obat juga tidak bisa diberikan karena stok tidak ada untuk pasien tersebut
![Screenshot from 2021-08-21 13-40-02](https://user-images.githubusercontent.com/44671357/130313367-b64c63e3-67c5-4049-8d81-85eeb52e3e70.png)

7. Bahkan di kartu stok nurse station, obat fenobarbital tidak ditemukan
![Screenshot from 2021-08-21 13-40-24](https://user-images.githubusercontent.com/44671357/130313377-ce660155-3fe3-41a8-8bad-13639574611d.png)

8. Permintaan mutasi dari apotek - nurse station masuk
![Screenshot from 2021-08-21 13-41-33](https://user-images.githubusercontent.com/44671357/130313391-87733d87-7566-4e6c-ba8f-7c92a3179edc.png)

9. Setelah diterima baru resep dapat diberikan. Dan stok pada apotek berkurang sebanyak 4
![Screenshot from 2021-08-21 13-41-59](https://user-images.githubusercontent.com/44671357/130313400-d82cc011-d7f3-454a-bdbb-309236e9a518.png)
![Screenshot from 2021-08-21 13-42-05](https://user-images.githubusercontent.com/44671357/130313404-7e0c2406-3339-40d2-8792-0c6849288b55.png)
![Screenshot from 2021-08-21 13-43-31](https://user-images.githubusercontent.com/44671357/130313460-6d363942-31f5-46fb-a2bb-d4817d8406d3.png)

10. Pada pemberian pertama stok ada 4 feno dan 5 pctml
![Screenshot from 2021-08-21 13-42-10](https://user-images.githubusercontent.com/44671357/130313424-277b597d-c909-46f6-9fe6-b102c43c3d99.png)

11. Tercatat di riwayat
![Screenshot from 2021-08-21 13-42-20](https://user-images.githubusercontent.com/44671357/130313430-a6bdfbfd-9a04-4f36-9a40-53f176f38539.png)

12. Pemberian kedua sudah berkurang menjadi feno 3 dan pctml 4
![Screenshot from 2021-08-21 13-42-35](https://user-images.githubusercontent.com/44671357/130313437-c9a573fb-8ae0-4641-afef-f38c000708ee.png)

13. Dapat  di cek di kartu stok yang mencatat barang masuk dan barang keluar tadi
![Screenshot from 2021-08-21 13-42-57](https://user-images.githubusercontent.com/44671357/130313451-498ad413-3fa7-4c74-933c-3bf382ff80e3.png)

14. Pengembalian Obat
![Screenshot from 2021-08-21 13-44-02](https://user-images.githubusercontent.com/44671357/130313466-4e73ca7a-2cb5-44cb-9a8f-fab71343a2c0.png)

15. Pengembalian obat akan membuat permintaan mutasi
![Screenshot from 2021-08-21 13-44-22](https://user-images.githubusercontent.com/44671357/130313479-d35f2578-0496-48b5-869b-fc470a6cfa89.png)

16. Apotek menerima permintaan mutasi
![Screenshot from 2021-08-21 13-44-53](https://user-images.githubusercontent.com/44671357/130313486-e975c1d5-db12-465c-a9f3-dc9a62be9479.png)

17. Pada kartu stok apotek dapat dilihat barang sudah kembali
![Screenshot from 2021-08-21 13-45-13](https://user-images.githubusercontent.com/44671357/130313499-f188142d-3b32-47d1-9291-3bf6f9b8e967.png)

Dari hasil pengujian di atas saya tidak menemukan kendala bang pada saat mutasi stok, pemberian obat, maupun pengembalian sisa obat.

**Comment by septia-anugrah** [comment]
https://user-images.githubusercontent.com/15723622/130411814-cac63470-558a-4a82-b5bb-30d0c0766d40.mp4

seperti diatas kasusnya bang. setelah diserahkan dan di refresh di perawat tombolnya langsung berubah menjadi berikan padahal belum di lakukan terima mutasi
