### ISSUE TITLE
Penanda di tab racikan menu verifikasi jika terdapat obat racikan

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#424]
![image](https://user-images.githubusercontent.com/15723622/130318081-f28aa4fd-b2c0-4be4-9da6-4e32e7e17d6a.png)

**Comment by theycantrevealus** [comment]
Notif tentang jumlah resep dan racikan dan status kajian
![Screenshot from 2021-08-21 18-15-00](https://user-images.githubusercontent.com/44671357/130320072-73e3c1ab-b8a0-482e-bcac-0de07b7a817b.png)

Jika kajian sudah diisi maka akan ada tanda check
![Screenshot from 2021-08-21 18-15-05](https://user-images.githubusercontent.com/44671357/130320088-4ca32f24-2183-4ae0-be1c-6f516cda37a4.png)

**Comment by septia-anugrah** [comment]
Done
