### ISSUE TITLE
[Rajal] Di CPPT pasien saya, Resep racikan apotek sudah tampil walaupun resep belum diverifikasi

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#425]
https://user-images.githubusercontent.com/15723622/130339109-c1ee1930-4dd0-4e59-9b1b-902fb0718e06.mp4

resep racikan yang belum diverifikasi, di CPPT sudah tampil resep racikannya. seharusnya yang tampil adalah keterangan belum diverifikasi

**Comment by theycantrevealus** [comment]
![Screenshot from 2021-08-24 14-00-02](https://user-images.githubusercontent.com/44671357/130578977-93ab8579-2eb1-4173-9acd-983272ffe1de.png)
