### ISSUE TITLE
[Kartu Stok Apotek] Terdapat perbedaan antara jumlah stok di list dengan jumlah stok di detail

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#431]
**Judul**: [Kartu Stok Apotek] Terdapat perbedaan antara jumlah stok di list kartu stok dengan jumlah stok di detail kartu stok

**Permasalahan**: 
Awalnya stok catapres dan cendo lfx di kartu stok masing masing adalah 0 sebelum di amprah
![erjserns](https://user-images.githubusercontent.com/15723622/130575162-89b31c24-a6dd-43a8-9995-bba3293ce8fa.png)

Setelah diamprah sebanyak masing masing 100 dan 50. di list kartu stok totalnya menjadi seperti dibawah ini
![catapres](https://user-images.githubusercontent.com/15723622/130575529-5c056f24-5f26-4a7d-a0c0-3855c8b91299.png)
dua kali lipat

sementara di detail kartu stok. mutasinya sudah benar
![svdyf](https://user-images.githubusercontent.com/15723622/130575706-fc2479fd-a104-4bed-9667-dfc82b629631.png)
![ersenh](https://user-images.githubusercontent.com/15723622/130575722-6a7e73e0-69b6-441a-9492-b0ba227ee670.png)

**Ekspektasi**: Jumlah stok di list kartu stok dan di detail kartu stok bisa sama 
                  atau berikan klarifikasi kenapa hal tersebut bisa terjadi

berikut dilampirkan video saat amprah:

https://user-images.githubusercontent.com/15723622/130576170-e648468d-9ed0-477e-8d0e-a997917a07a1.mp4

**Comment by theycantrevealus** [comment]
Linked #380 
Akan diagendakan untuk mutasi stok pada kunjungan selanjutnya untuk menyamakan stok. Ini merupakan permasalahan pada data dan bukan pada fitur. Kemarin sudah disepakati untuk ini.
![Screenshot from 2021-08-24 14-50-49](https://user-images.githubusercontent.com/44671357/130578377-9833d83d-bebb-4840-b4af-64b17f8861a8.png)
