### ISSUE TITLE
[BUG] - (Kasir Rajal) Setelah verifikasi lab, nama pasien tidak muncul dikasir

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#434]
**Keterangan Bug (REQUIRED)**
>Keterangan lengkap tentang bug.
Setelah dilakukan verifikasi lab oleh petugas, nama pasien tidak muncul di kasir.
Telah dipilih opsi show all dan dilakukan pencarian di kolom search namun nama pasien masih belum ditemukan

kasus pada poli THT dokter Yuhana

**Kondisi Kemunculan Bug (REQUIRED)**
>Error akan muncul pada saat metode pengujian dengan tahapan:

1. Petugas lab melakukan verifikasi dan klik selesai
2. Petugas kasir mencari nama pasien yang akan di proses biaya pemeriksaannya
3. Notifikasi tagihan baru muncul di kasir

**Kondisi yang Diharapkan (REQUIRED)**
>Deskripsikan kondisi yang diharapkan.
Nama pasien dapat muncul di kasir dan dapat diteruskan ke proses pengisian hasil lab

**Screenshots (REQUIRED)**
>Screenshot kemunculan bug.
berikut video kemunculan bug
https://user-images.githubusercontent.com/15723622/130752373-b57c68b8-158f-44fa-8316-a572fc6a3e4b.mp4

**Keterangan Tambahan (OPTIONAL)**
>Keterangan tambahan.

...................................isian disini.....................................

**Comment by theycantrevealus** [comment]
Muncul tuh bang Sdr. Peruji. Sudah cek cache bang?
![Screenshot from 2021-08-25 15-43-26](https://user-images.githubusercontent.com/44671357/130758604-f57cd218-7cf9-46b0-985b-66961f089af0.png)

**Comment by septia-anugrah** [comment]
Oke done bang
