### ISSUE TITLE
[BUG] - (Kasir Rajal) Setelah verifikasi radiologi, nama pasien tidak muncul dikasir

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#435]
**Keterangan Bug (REQUIRED)**
>Keterangan lengkap tentang bug.

Setelah dilakukan verifikasi lab oleh petugas, nama pasien tidak muncul di kasir.
Telah dipilih opsi show all dan dilakukan pencarian di kolom search namun nama pasien masih belum ditemukan

kasus pada poli THT dokter Yuhana

**Kondisi Kemunculan Bug (REQUIRED)**
>Error akan muncul pada saat metode pengujian dengan tahapan:

Petugas lab melakukan verifikasi dan klik selesai
Petugas kasir mencari nama pasien yang akan di proses biaya pemeriksaannya
Notifikasi tagihan baru muncul di kasir

**Kondisi yang Diharapkan (REQUIRED)**
>Deskripsikan kondisi yang diharapkan.

Nama pasien dapat muncul di kasir dan dapat diteruskan ke proses pengisian hasil radiologi

**Screenshots (REQUIRED)**
>Screenshot kemunculan bug.
berikut video kemunculan bug
https://user-images.githubusercontent.com/15723622/130752974-d9ce5430-4f6e-4cf8-b2b2-576420b2e91a.mp4

**Keterangan Tambahan (OPTIONAL)**
>Keterangan tambahan.

...................................isian disini.....................................

**Comment by theycantrevealus** [comment]
Linked to #434 
![Screenshot from 2021-08-25 15-43-26](https://user-images.githubusercontent.com/44671357/130759242-de3d3dae-db8b-47cf-aca0-b1e3c69ccfd3.png)

**Comment by septia-anugrah** [comment]
Oke done bang
