### ISSUE TITLE
[BUG] - (Amprah Apotek) Total stok di list kartu stok dan detail kartu stok masih belum sama

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#436]
**Keterangan Bug (REQUIRED)**
>Keterangan lengkap tentang bug.
Seperti issue sebelumnya. total stok di list kartu stok dan di detail kartu stok apotek masih berbeda.
Polanya adalah total di list dua kali dari total di detail

berdasarkan info yang didapatkan. data stok lama sudah dibersihkan
![image](https://user-images.githubusercontent.com/15723622/130755295-5e02cffd-33d9-470c-a647-d89049b03d3d.png)

**Kondisi Kemunculan Bug (REQUIRED)**
>Error akan muncul pada saat metode pengujian dengan tahapan:

1. Petugas apotek melihat stok heliatech dan kalsium 0
2. lalu petugas melakukan amprah heliatech dan kalsium masing masing 20 dan 10
3. Setelah amprah disetujui petugas mengecek stok yang masuk
4. Di list kartu stok total stok heliatech berubah menjadi 40 dan kalsium 20
5. Di detail kartu stok, stok helaitech yang masuk betul sebanyak 20 dan kalsium sebanyak 10

**Kondisi yang Diharapkan (REQUIRED)**
>Deskripsikan kondisi yang diharapkan.
Jumlah stok di list kartu stok dan di detail kartu stok bisa sama sehingga user mendapatkan perhitungan jumlah yang sesuai

**Screenshots (REQUIRED)**
>Screenshot kemunculan bug.
Stok heliatech dan kalsium 0
![tuja](https://user-images.githubusercontent.com/15723622/130757121-19f94f72-3c1c-4e74-875e-acc759172677.png)

Setelah diamprah sebanyak masing masing 20 dan 10. di total stok menjadi 40 dan 20
![masih cok](https://user-images.githubusercontent.com/15723622/130757613-c51931ce-526c-48cc-9cb8-99a3d3acdd0a.png)

berikut detail stok heliatech
![per](https://user-images.githubusercontent.com/15723622/130757386-82634da9-b7c9-4070-99e6-c7600a6485b4.png)

berikut detail stok kalsium
![3](https://user-images.githubusercontent.com/15723622/130757528-71aa2e54-e8f8-451a-8f82-5aabaa576309.png)

berikut videonya

https://user-images.githubusercontent.com/15723622/130754472-e340a9fb-057c-432f-93b1-b89a19464ece.mp4

**Keterangan Tambahan (OPTIONAL)**
>Keterangan tambahan.

**Comment by theycantrevealus** [comment]
Seperti yang saya jelaskan di #431 
Harus dilaksanakan **stok opname** untuk mendapatkan stok yang sesuai antara di stok aktual dan history pergerakkan stok.

>Kenapa sekarang tidak sesuai neh?

>Karena dulu pernah diadakan uji stok awal dengan jumlah yang sudah diimport pada sistem. namun setelah melakukan uji berulang yang membuat data pergerakan stok menjadi banyak. Sifat dari kartu stok adalah rekapitulasi semua traffic transaction pada suatu obat baik dari proses resep apotek, amprah, delivery order, dll. Hal ini menyebabkan kesulitan dalam menguji satu proses. Maka dari itu dilakukan reset transact log untuk mempermudah pengujian model lalu lintas stok. Saya kira ini sudah lama diuji dan tidak ada masalah saat uji dulu.

Berikut saya coba demokan antara item yang di stok awal **Asam Mefenamat Tablet 500mg** dengan stok berjalan dari pertengahan proses uji coba **Parasetamol.**

1. Dapat dilihat stok pada apotek asam mefenamat kosong.
![Screenshot from 2021-08-25 15-56-28](https://user-images.githubusercontent.com/44671357/130763074-6ec10032-39f7-4842-b921-c902e8833579.png)

2. Dilakukan amprah asam mefenamat qty:200
![Screenshot from 2021-08-25 15-57-00](https://user-images.githubusercontent.com/44671357/130763089-9373d16c-3a70-4b8d-98fc-9052413704b3.png)

3. Pada stok gudang utama juga kosong
![Screenshot from 2021-08-25 15-57-32](https://user-images.githubusercontent.com/44671357/130763164-5e38deea-85c0-4e96-a78a-6bf0cc754439.png)

4. Gudang utama melakukan order untuk mengadakan stok pada gudang utama
![Screenshot from 2021-08-25 15-57-56](https://user-images.githubusercontent.com/44671357/130763260-807a38a7-a22a-4c5a-bab3-ea9940152d4c.png)

5. Gudang Utama terima barang
![Screenshot from 2021-08-25 15-58-43](https://user-images.githubusercontent.com/44671357/130763310-eb8e51fa-5712-4cb2-82e9-7a898c922eb9.png)

6. Terlihat stok sudah maasuk. Antara jumlah stok di luar dan didalam sama karena pergerakan stok direkam sejak awal pengadaan. Hal yang sama juga pada saat stok opname nantinya.
![Screenshot from 2021-08-25 15-59-11](https://user-images.githubusercontent.com/44671357/130763443-c53c8131-e092-46b7-b8ce-13d90b1b77e8.png)
![Screenshot from 2021-08-25 15-59-19](https://user-images.githubusercontent.com/44671357/130763465-07502460-3ce6-4b17-bad8-abffb114cc72.png)

7. Proses permintaan amprah dari utari
![Screenshot from 2021-08-25 15-59-43](https://user-images.githubusercontent.com/44671357/130763551-adb01153-b28c-4111-86a2-e600eb2f14af.png)

8. Stok pada gudang utama berkurang
![Screenshot from 2021-08-25 15-59-58](https://user-images.githubusercontent.com/44671357/130763599-5575237e-68af-4c79-a2b9-07d585d253ce.png)
![Screenshot from 2021-08-25 16-00-02](https://user-images.githubusercontent.com/44671357/130763663-7b749e26-f355-4b9e-acc0-13f95ede73b9.png)

9. Stok utari bertambah
![Screenshot from 2021-08-25 16-00-39](https://user-images.githubusercontent.com/44671357/130763703-3a386173-f747-491c-9f55-e03a1f39ae56.png)
![Screenshot from 2021-08-25 16-00-43](https://user-images.githubusercontent.com/44671357/130763715-d6dded9a-b0fc-4490-9271-5c15b346cd77.png)

10. Diuji kembali dengan stok yang tidak terekam sejak awal pergerakan stok seperti **parasetamol**
![Screenshot from 2021-08-25 16-02-01](https://user-images.githubusercontent.com/44671357/130763832-bd2422f2-228a-440b-9c8e-c276193d86e2.png)

11. Pemotongan stok setelah amprah
![Screenshot from 2021-08-25 16-04-07](https://user-images.githubusercontent.com/44671357/130763919-0ba067c6-ef98-4bbe-af98-4ea2313f5529.png)
![Screenshot from 2021-08-25 16-04-59](https://user-images.githubusercontent.com/44671357/130764016-675aac1e-e2c2-4654-bfe5-8dbc0082ec95.png)

Simulasi barang masuk dan barang keluar valid. Yang tidak valid adalah data aktual di sistem. Mohon dipahami adalah sistem ini sedang **DEV MODE**. Data yang di dalam tidak semuanya valid. Hanya sebagai uji model simulasi. **Correct me if I wrong**

**Comment by theycantrevealus** [comment]
Humble Reminder. It is linked ad #431 .
