### ISSUE TITLE
[BUG] - (Rajal Perawat) Menu perawat waktu load lebih lama daripada menu lainnya

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#437]
**Keterangan Bug (REQUIRED)**
>Keterangan lengkap tentang bug.
Menu perawat waktu loadnya lebih lama dari menu lainnya. 

Setelah dilakukan perbandingan menu perawat dengan menu dokter side by side. menu perawat diketahui memiliki waktu load yang lebih lama. jika disebabkan oleh jaringan, maka halaman dokter akan cenderung lama juga waktu load

browser yang digunakan adalah mozilla firefox dan cache sudah dibersihkan.

**Kondisi Kemunculan Bug (REQUIRED)**
>Error akan muncul pada saat metode pengujian dengan tahapan:

1.  Pengguna yaitu perawat membuka halaman list pasien
2. Halaman list asesmen berat saat diload
3. Saat perawat mencoba mengganti dokter, select2 nama dokter berat untuk dipilih  

**Kondisi yang Diharapkan (REQUIRED)**
>Deskripsikan kondisi yang diharapkan.
Halaman dapat diload dengan waktu yang lebih singkat

**Screenshots (REQUIRED)**
>Screenshot kemunculan bug.
berikut videonya
https://user-images.githubusercontent.com/15723622/130757779-b0c3aa8e-47b7-48a9-bbe3-a726a06a595f.mp4

**Keterangan Tambahan (OPTIONAL)**
>Keterangan tambahan.

...................................isian disini.....................................

**Comment by theycantrevealus** [comment]
https://user-images.githubusercontent.com/44671357/130771484-aa05cb9d-1e71-450c-af18-b8b1fb8219b9.mp4
