### ISSUE TITLE
[FEATURE REQUEST] - Alasan mutasi dibuat menjadi required

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#465]
**Apakah fitur terkait dengan sebuah permasalahan? (OPTIONAL)**
>Alur Kerja dan permasalahan. Deskripsikan masalah secara terperinci dengan alur kejadian. 

Keterangan Mutasi dibuat menjadi wajib. agar setiap user melakukan mutasi dilengkapi dengan alasan/keterangan

Uploading mutasi alasan masih belum wajib.mp4…

**Solusi (REQUIRED)**
>Deskripsikan solusi yang Anda kaji dan sepakati dengan tim. Solusi penyelesaian pada fitur dan syarat kondisi pada penyelesaian secara terperinci.

...................................isian disini.....................................

**Solusi Cadangan /sebagai pertimbangan (OPTIONAL)**
>Jika solusi utama tidak dapat terpenuhi karena kondisi tertentu.

...................................isian disini.....................................

**Keterangan Tambahan (OPTIONAL)**
>Keterangan tambahan untuk fitur yang diminta.

...................................isian disini.....................................

**Comment by theycantrevealus** [comment]
#473 Merge Mark

**Comment by septia-anugrah** [comment]
oke done
