### ISSUE TITLE
[BUG] - (Kamar Operasi) Setelah simpan data pasca operasi. tagihan tidak ada di kasir

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#467]
**Keterangan Bug (REQUIRED)**
>Keterangan lengkap tentang bug.

Setelah dilakukan pengisian data pemakaian obat/bhp pasca operasi. tidak ada tagihan di kasir

**Kondisi Kemunculan Bug (REQUIRED)**
>Error akan muncul pada saat metode pengujian dengan tahapan:

1. Dilakukan penambahan jadwal operasi
2. Dilakukan pengisian paket pra operasi
3. Dilakukan pengisian data pasca operasi

**Kondisi yang Diharapkan (REQUIRED)**
>Deskripsikan kondisi yang diharapkan.

Diberikan penjelasan mengenai tahapan dalam menggunakan menu kamar operasi

**Screenshots (REQUIRED)**
>Screenshot kemunculan bug.

https://user-images.githubusercontent.com/15723622/135219419-329d3fb1-c39c-45a5-be0f-f832983921b4.mp4

**Keterangan Tambahan (OPTIONAL)**
>Keterangan tambahan.

...................................isian disini.....................................

**Comment by theycantrevealus** [comment]
#472 Merge Mark

**Comment by septia-anugrah** [comment]
Gagal menabahkan jadwal 

![Image 14](https://user-images.githubusercontent.com/15723622/135701679-547370ed-6f9d-41e9-a2aa-4df63106f456.png)

**Comment by septia-anugrah** [comment]
Tagihan pasca operasi obat parasetamol dan metformin tidak muncul di tagihan pasien abbas
Padahal stok parasetamol dan metformin ada di depo OK sebanyak masing- masing 30
https://user-images.githubusercontent.com/15723622/135812562-4bf97d39-b5bd-4d75-b68a-f5a08764c0f1.mp4
