### ISSUE TITLE
[FEATURE REQUEST] - (Farmasi) Urutan saran gudang pada saat verifikasi apotek.

### ISSUE THREAD

**Issue by septia-anugrah** [theycantrevealus/PDC00001#468]
**Apakah fitur terkait dengan sebuah permasalahan? (OPTIONAL)**
>Alur Kerja dan permasalahan. Deskripsikan masalah secara terperinci dengan alur kejadian. 

Urutannya dibuat menjadi apotek -> gudang farmasi -> unit lain lain
![urutan](https://user-images.githubusercontent.com/15723622/135219198-95e3de5a-887e-4e13-819b-345c6e73a27d.png)

**Solusi (REQUIRED)**
>Deskripsikan solusi yang Anda kaji dan sepakati dengan tim. Solusi penyelesaian pada fitur dan syarat kondisi pada penyelesaian secara terperinci.

**Solusi Cadangan /sebagai pertimbangan (OPTIONAL)**
>Jika solusi utama tidak dapat terpenuhi karena kondisi tertentu.

...................................isian disini.....................................

**Keterangan Tambahan (OPTIONAL)**
>Keterangan tambahan untuk fitur yang diminta.

...................................isian disini.....................................

**Comment by theycantrevealus** [comment]
#472 Merge Mark
